// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/inventory.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_AddPainting_FullMethodName    = "/inventory.InventoryService/AddPainting"
	InventoryService_UpdatePainting_FullMethodName = "/inventory.InventoryService/UpdatePainting"
	InventoryService_RemovePainting_FullMethodName = "/inventory.InventoryService/RemovePainting"
	InventoryService_GetPainting_FullMethodName    = "/inventory.InventoryService/GetPainting"
	InventoryService_ListPaintings_FullMethodName  = "/inventory.InventoryService/ListPaintings"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service definition
type InventoryServiceClient interface {
	AddPainting(ctx context.Context, in *Painting, opts ...grpc.CallOption) (*Painting, error)
	UpdatePainting(ctx context.Context, in *Painting, opts ...grpc.CallOption) (*Painting, error)
	RemovePainting(ctx context.Context, in *Painting, opts ...grpc.CallOption) (*Painting, error)
	GetPainting(ctx context.Context, in *Painting, opts ...grpc.CallOption) (*Painting, error)
	ListPaintings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Painting], error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) AddPainting(ctx context.Context, in *Painting, opts ...grpc.CallOption) (*Painting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Painting)
	err := c.cc.Invoke(ctx, InventoryService_AddPainting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) UpdatePainting(ctx context.Context, in *Painting, opts ...grpc.CallOption) (*Painting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Painting)
	err := c.cc.Invoke(ctx, InventoryService_UpdatePainting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) RemovePainting(ctx context.Context, in *Painting, opts ...grpc.CallOption) (*Painting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Painting)
	err := c.cc.Invoke(ctx, InventoryService_RemovePainting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetPainting(ctx context.Context, in *Painting, opts ...grpc.CallOption) (*Painting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Painting)
	err := c.cc.Invoke(ctx, InventoryService_GetPainting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ListPaintings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Painting], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InventoryService_ServiceDesc.Streams[0], InventoryService_ListPaintings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, Painting]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InventoryService_ListPaintingsClient = grpc.ServerStreamingClient[Painting]

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
//
// The service definition
type InventoryServiceServer interface {
	AddPainting(context.Context, *Painting) (*Painting, error)
	UpdatePainting(context.Context, *Painting) (*Painting, error)
	RemovePainting(context.Context, *Painting) (*Painting, error)
	GetPainting(context.Context, *Painting) (*Painting, error)
	ListPaintings(*Empty, grpc.ServerStreamingServer[Painting]) error
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) AddPainting(context.Context, *Painting) (*Painting, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPainting not implemented")
}
func (UnimplementedInventoryServiceServer) UpdatePainting(context.Context, *Painting) (*Painting, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePainting not implemented")
}
func (UnimplementedInventoryServiceServer) RemovePainting(context.Context, *Painting) (*Painting, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePainting not implemented")
}
func (UnimplementedInventoryServiceServer) GetPainting(context.Context, *Painting) (*Painting, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPainting not implemented")
}
func (UnimplementedInventoryServiceServer) ListPaintings(*Empty, grpc.ServerStreamingServer[Painting]) error {
	return status.Errorf(codes.Unimplemented, "method ListPaintings not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_AddPainting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Painting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).AddPainting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_AddPainting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).AddPainting(ctx, req.(*Painting))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_UpdatePainting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Painting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).UpdatePainting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_UpdatePainting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).UpdatePainting(ctx, req.(*Painting))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_RemovePainting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Painting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).RemovePainting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_RemovePainting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).RemovePainting(ctx, req.(*Painting))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetPainting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Painting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetPainting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetPainting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetPainting(ctx, req.(*Painting))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ListPaintings_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InventoryServiceServer).ListPaintings(m, &grpc.GenericServerStream[Empty, Painting]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InventoryService_ListPaintingsServer = grpc.ServerStreamingServer[Painting]

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPainting",
			Handler:    _InventoryService_AddPainting_Handler,
		},
		{
			MethodName: "UpdatePainting",
			Handler:    _InventoryService_UpdatePainting_Handler,
		},
		{
			MethodName: "RemovePainting",
			Handler:    _InventoryService_RemovePainting_Handler,
		},
		{
			MethodName: "GetPainting",
			Handler:    _InventoryService_GetPainting_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListPaintings",
			Handler:       _InventoryService_ListPaintings_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/inventory.proto",
}
