// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/inventory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The painting message
type Painting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	StockQuantity int32                  `protobuf:"varint,6,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Painting) Reset() {
	*x = Painting{}
	mi := &file_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Painting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Painting) ProtoMessage() {}

func (x *Painting) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Painting.ProtoReflect.Descriptor instead.
func (*Painting) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Painting) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Painting) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Painting) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Painting) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Painting) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Painting) GetStockQuantity() int32 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

// Empty message for requests with no data
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{1}
}

var File_proto_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"\x15proto/inventory.proto\x12\tinventory\"\xa7\x01\n" +
	"\bPainting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12%\n" +
	"\x0estock_quantity\x18\x06 \x01(\x05R\rstockQuantity\"\a\n" +
	"\x05Empty2\xb6\x02\n" +
	"\x10InventoryService\x127\n" +
	"\vAddPainting\x12\x13.inventory.Painting\x1a\x13.inventory.Painting\x12:\n" +
	"\x0eUpdatePainting\x12\x13.inventory.Painting\x1a\x13.inventory.Painting\x12:\n" +
	"\x0eRemovePainting\x12\x13.inventory.Painting\x1a\x13.inventory.Painting\x127\n" +
	"\vGetPainting\x12\x13.inventory.Painting\x1a\x13.inventory.Painting\x128\n" +
	"\rListPaintings\x12\x10.inventory.Empty\x1a\x13.inventory.Painting0\x01B\x19Z\x17inventory-service/protob\x06proto3"

var (
	file_proto_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_proto_rawDescData []byte
)

func file_proto_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_proto_rawDescData
}

var file_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_inventory_proto_goTypes = []any{
	(*Painting)(nil), // 0: inventory.Painting
	(*Empty)(nil),    // 1: inventory.Empty
}
var file_proto_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.InventoryService.AddPainting:input_type -> inventory.Painting
	0, // 1: inventory.InventoryService.UpdatePainting:input_type -> inventory.Painting
	0, // 2: inventory.InventoryService.RemovePainting:input_type -> inventory.Painting
	0, // 3: inventory.InventoryService.GetPainting:input_type -> inventory.Painting
	1, // 4: inventory.InventoryService.ListPaintings:input_type -> inventory.Empty
	0, // 5: inventory.InventoryService.AddPainting:output_type -> inventory.Painting
	0, // 6: inventory.InventoryService.UpdatePainting:output_type -> inventory.Painting
	0, // 7: inventory.InventoryService.RemovePainting:output_type -> inventory.Painting
	0, // 8: inventory.InventoryService.GetPainting:output_type -> inventory.Painting
	0, // 9: inventory.InventoryService.ListPaintings:output_type -> inventory.Painting
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_inventory_proto_init() }
func file_proto_inventory_proto_init() {
	if File_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_proto = out.File
	file_proto_inventory_proto_goTypes = nil
	file_proto_inventory_proto_depIdxs = nil
}
